repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Última versão estável
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
