version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
    volumes:
      - .:/app  # Sincroniza o código local com o container
      - sqlite_data:/app  # Persistência do banco no container
    env_file:
      - .env.docker 
    entrypoint: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:${DJANGO_PORT:-8000}"

volumes:
  sqlite_data:
