version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
    volumes:
      - .:/app  # Código local -> Caminho no container
      - ${DB_SQLITE_HOST_PATH:-./db.sqlite3}:${DB_SQLITE_PATH:-/app/db.sqlite3}  # Banco persistente
    env_file:
      - .env.docker
    entrypoint: >
      sh -c "
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:${DJANGO_PORT:-8000} TCC.wsgi:application"
