# Generated by Django 4.2.13 on 2024-11-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
