# Generated by Django 4.2.16 on 2024-11-23 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("correction", "0003_answer_extract_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-11-11 00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="turma",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
